<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);RMG012;RMG020</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClosedXML" Version="0.105.1" />
        <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.2" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0" />
        <PackageReference Include="WebPush" Version="1.0.13" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\DTO\DTO.csproj" />
        <ProjectReference Include="..\Interface\Interface.csproj" />
        <ProjectReference Include="..\Validator\Validator.csproj" />
    </ItemGroup>

</Project>
